# Generated by Django 2.2b1 on 2019-03-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_remove_group_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Country')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOW', 'Widow')], max_length=9)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to=users.utils.get_image_filename)),
                ('mobile_number', models.CharField(blank=True, max_length=12)),
                ('date_of_birth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('id_number', models.IntegerField(verbose_name='ID Number')),
                ('passport_number', models.CharField(blank=True, max_length=16)),
                ('nationality', models.CharField(max_length=36)),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Residential address')),
                ('town', models.CharField(blank=True, max_length=30)),
                ('user_group', models.ForeignKey(on_delete=models.SET(None), to='auth.Group')),
            ],
        ),
    ]
