# Generated by Django 2.2 on 2019-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cr_ac_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dr_ac_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
