# Generated by Django 2.2.7 on 2019-11-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_locations', to='support_data.DutyStation'),
        ),
    ]
