# Generated by Django 2.2 on 2019-10-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0002_auto_20191011_1027'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='kin_date_of_birth',
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_location', to='support_data.DutyStation'),
        ),
    ]
