# Generated by Django 2.2 on 2019-04-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='earning_and_deductions_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.EarningDeductionCategory'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='earning_and_deductions_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.EarningDeductionType'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
