# Generated by Django 2.2b1 on 2019-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(
                choices=[('Recruit', 'RECRUIT'), ('Approved', 'APPROVED'), ('Terminated', 'TERMINATED')],
                default='Recruit', max_length=17),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
