# Generated by Django 2.2 on 2019-05-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('approve_employee', 'Can approve Employee')]},
        ),
    ]
