# Generated by Django 2.2 on 2019-04-07 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190406_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=30, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='exit_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='notice_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='termination_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
