# Generated by Django 2.2 on 2019-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191012_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemovement',
            name='remarks',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
