# Generated by Django 2.2 on 2019-08-20 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190820_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_bank', to='payroll.Bank', verbose_name='Bank 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_bank', to='payroll.Bank', verbose_name='Bank 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.ContractType', verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CostCentre', verbose_name='Cost Centre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cr_ac_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CR A/C code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='D.O.B'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dr_ac_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DR A/C code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_account_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='A/C No.1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_bank_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ID No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.JobTitle', verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.Relationship', verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_insurance_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.MedicalInsuranceCategory', verbose_name='Medical Insurance Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_insurance_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medical Insurance No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Passport No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.PaymentType', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_account_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='A/C No.2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_bank_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='Security Security'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Security No.'),
        ),
    ]
