# Generated by Django 2.2b1 on 2019-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20190325_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(
                choices=[('Recruit', 'RECRUIT'), ('Approved', 'APPROVED'), ('Terminated', 'TERMINATED'),
                         ('Rejected', 'REJECTED')], default='Recruit', max_length=17),
        ),
    ]
