# Generated by Django 2.2 on 2019-09-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0002_movementparameter'),
        ('users', '0002_terminatedemployees_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('move_from', models.CharField(blank=True, max_length=150, null=True)),
                ('move_to', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Employee')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='support_data.MovementParameter')),
            ],
        ),
    ]
