# Generated by Django 2.2b1 on 2019-03-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20190329_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_key',
            field=models.CharField(blank=True, default=None, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='PayrollPeriodReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
        ),
    ]
