# Generated by Django 2.2 on 2019-05-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190505_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='project_key',
            field=models.CharField(blank=True, default=None, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='contribution_percentage',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
    ]
