# Generated by Django 2.2 on 2019-04-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190422_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='earning_and_deductions_type',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='payroll.EarningDeductionType'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_key',
            field=models.CharField(blank=True, default=None, editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
