# Generated by Django 3.0.6 on 2020-06-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200604_0357'),
        ('payroll', '0007_auto_20200602_0958'),
        ('users', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprocessors',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earning_or_deduction', to='reports.ExTraSummaryReportInfo'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollPeriod'),
        ),
    ]
