# Generated by Django 2.2 on 2019-05-17 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190518_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='days_given',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='exit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='notice_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='terminatedemployees',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
