# Generated by Django 2.2 on 2019-04-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190423_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='earning_and_deductions_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.EarningDeductionType'),
        ),
    ]
