# Generated by Django 2.2.7 on 2019-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191106_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollCenter'),
        ),
    ]
