# Generated by Django 2.2 on 2019-05-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190507_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='project_key',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
