# Generated by Django 2.2 on 2019-05-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190529_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
