# Generated by Django 2.2 on 2019-10-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20191011_1027'),
        ('users', '0003_auto_20191022_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='earnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.EarningDeductionType'),
        ),
    ]
