# Generated by Django 2.2 on 2019-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employeemovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('approve_employee', 'Can approve Employee'), ('terminate_employee', 'Can terminate Employee'), ('assign_employee', 'Can assign Project'), ('can_change_user_group', 'Can change user group'), ('can_approve_payroll_summary', 'Can approve payroll summary')]},
        ),
    ]
