# Generated by Django 2.2 on 2019-04-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190407_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminatedemployees',
            name='termination_date',
        ),
    ]
