# Generated by Django 2.2b1 on 2019-03-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0004_auto_20190329_1231'),
        ('users', '0003_auto_20190329_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodreport',
            name='lst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.LSTRates'),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='nssf',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='paye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PAYERates'),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
