# Generated by Django 2.2 on 2019-08-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190820_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3, null=True, verbose_name='Security Security'),
        ),
    ]
