# Generated by Django 2.2 on 2019-05-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190529_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('RECRUIT', 'Recruit'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TERMINATED', 'Terminated')], db_index=True, default='RECRUIT', max_length=17, null=True),
        ),
    ]
