# Generated by Django 2.2b1 on 2019-03-29 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20190329_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollPeriodReport',
        ),
    ]
