# Generated by Django 2.2 on 2019-05-17 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190518_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
    ]
