# Generated by Django 2.2 on 2019-05-11 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190510_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_key',
            field=models.CharField(blank=True, default=None, editable=False, max_length=150),
        ),
    ]
