# Generated by Django 2.2 on 2019-04-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190423_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
