# Generated by Django 2.2 on 2019-08-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0001_initial'),
        ('users', '0004_auto_20190820_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sos_address_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_address_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_address_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_contact_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_contact_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_contact_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_relationship_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_relationship_1', to='support_data.Relationship', verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_relationship_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_relationship_2', to='support_data.Relationship', verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_relationship_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_relationship_3', to='support_data.Relationship', verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, null=True, verbose_name='Security Security'),
        ),
    ]
