# Generated by Django 3.0.6 on 2020-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200604_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK', 'BANK'), ('CASH', 'CASH')], max_length=4, null=True),
        ),
    ]
