# Generated by Django 2.2 on 2019-10-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employeemovement_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
