# Generated by Django 2.2.7 on 2019-11-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20191105_1252'),
        ('users', '0004_auto_20191107_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProcessorManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_status', models.CharField(default='NO', max_length=3)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollPeriod')),
            ],
        ),
    ]
