# Generated by Django 2.2 on 2019-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190518_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='days_given',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
