# Generated by Django 2.2 on 2019-05-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190511_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='contribution_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CostCentre'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='dea_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.DEA'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='sof_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SOF'),
        ),
    ]
