# Generated by Django 2.2 on 2019-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employeemovement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemovement',
            name='status',
            field=models.CharField(blank=True, default='SHOW', editable=False, max_length=20),
        ),
    ]
