# Generated by Django 2.2b1 on 2019-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_delete_payrollperiodreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
