# Generated by Django 2.2.7 on 2019-11-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payrollprocessormanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessormanager',
            name='payroll_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payroll.PayrollPeriod'),
        ),
    ]
