# Generated by Django 2.2 on 2019-06-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190529_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dea',
            name='sof_code',
        ),
        migrations.RemoveField(
            model_name='employeeproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeproject',
            name='project_key',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='sof',
            name='project_code',
        ),
    ]
