# Generated by Django 2.2 on 2019-08-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190821_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sos_contact_1',
            new_name='sos_name_1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sos_contact_2',
            new_name='sos_name_2',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sos_contact_3',
            new_name='sos_name_3',
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_phone_number_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency contact Phone No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_phone_number_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency contact Phone No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sos_phone_number_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency contact Phone No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sos_address_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sos_address_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sos_address_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Emergency contact address'),
        ),
    ]
