# Generated by Django 3.0.6 on 2020-06-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200604_1430'),
        ('users', '0005_employee_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprocessors',
            name='ss_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_or_deduction', to='reports.SocialSecurityReport'),
        ),
    ]
