# Generated by Django 3.0.6 on 2020-06-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20200604_1440'),
        ('users', '0006_payrollprocessors_ss_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprocessors',
            name='taxation_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_or_deduction', to='reports.TaxationReport'),
        ),
    ]
