# Generated by Django 2.2.7 on 2019-11-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191110_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollprocessormanager',
            name='id',
        ),
        migrations.AlterField(
            model_name='payrollprocessormanager',
            name='payroll_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payroll.PayrollPeriod'),
        ),
    ]
