# Generated by Django 2.2 on 2019-08-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0001_initial'),
        ('users', '0006_auto_20190821_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='kin_email',
        ),
        migrations.AddField(
            model_name='employee',
            name='kin_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kin_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kin_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.Nationality', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kin_passport_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Passport No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile numbers'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kin_relationship', to='support_data.Relationship', verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_nationality', to='support_data.Nationality'),
        ),
    ]
