# Generated by Django 2.2 on 2019-05-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190512_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='agresso_number',
            field=models.IntegerField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
    ]
