# Generated by Django 2.2 on 2019-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191023_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='extra_info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
