# Generated by Django 2.2 on 2019-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190605_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeproject',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='employee',
            field=models.ManyToManyField(related_name='employee_projects', to='users.Employee'),
        ),
    ]
