# Generated by Django 2.2 on 2019-06-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190605_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeproject',
            name='project_code',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
