# Generated by Django 2.2b1 on 2019-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_terminatedemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='days_given',
            field=models.IntegerField(null=True),
        ),
    ]
