# Generated by Django 2.2 on 2019-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190515_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agresso_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
