# Generated by Django 2.2 on 2019-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employeemovement_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='movement_requester',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='employeemovement',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected', to='users.Employee'),
        ),
    ]
