# Generated by Django 2.2 on 2019-05-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190518_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedemployees',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Employee'),
        ),
    ]
