# Generated by Django 2.2.7 on 2019-11-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191110_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprocessormanager',
            name='number_of_approvers',
            field=models.IntegerField(default=0),
        ),
    ]
