# Generated by Django 3.0.6 on 2020-06-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payrollprocessors_taxation_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollprocessors',
            name='ss_report',
        ),
    ]
