# Generated by Django 2.2 on 2019-06-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190605_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Project'),
        ),
    ]
