# Generated by Django 2.2 on 2019-05-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190515_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='project_code',
            new_name='project',
        ),
    ]
