# Generated by Django 2.2 on 2019-10-23 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191023_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemovement',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='employeemovement',
            name='movement_requester',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
