# Generated by Django 2.2 on 2019-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190518_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agresso_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
