# Generated by Django 2.2.7 on 2019-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payrollprocessormanager_number_of_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
