# Generated by Django 2.2b1 on 2019-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20190330_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollprocessors',
            name='id',
        ),
        migrations.AlterField(
            model_name='payrollprocessors',
            name='payroll_key',
            field=models.CharField(blank=True, default=None, max_length=150, primary_key=True, serialize=False,
                                   unique=True),
        ),
    ]
