# Generated by Django 2.2 on 2019-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0003_movementparameter_choice'),
        ('users', '0009_auto_20191023_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_locations',
            field=models.ManyToManyField(related_name='assigned_locations', to='support_data.DutyStation'),
        ),
    ]
