# Generated by Django 2.2 on 2019-05-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190515_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agresso_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
