# Generated by Django 2.2.7 on 2019-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employeemovement_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='over_time_category',
            field=models.CharField(blank=True, choices=[('Normal', 'NORMAL'), ('Weekend', 'WEEKEND')], max_length=10, null=True),
        ),
    ]
