# Generated by Django 2.2.7 on 2019-11-13 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employeemovement_over_time_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemovement',
            name='hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(22, 'Maximum hours are 22')]),
        ),
        migrations.AlterField(
            model_name='employeemovement',
            name='over_time_category',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('WEEKEND', 'Weekend')], max_length=10, null=True),
        ),
    ]
