# Generated by Django 2.2 on 2019-11-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20191104_1114'),
        ('users', '0010_employee_assigned_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemovement',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.PayrollPeriod'),
        ),
    ]
