# Generated by Django 2.2 on 2019-11-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employeemovement_payroll_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemovement',
            name='extra_info',
        ),
    ]
