# Generated by Django 2.2 on 2019-06-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190613_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('approve_employee', 'Can approve Employee'), ('terminate_employee', 'Can terminate Employee'), ('assign_employee', 'Can assign Project'), ('can_change_user_group', 'Can change user group')]},
        ),
    ]
