# Generated by Django 3.0.6 on 2020-09-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200924_0845'),
        ('users', '0015_auto_20200923_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprocessors',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earning_or_deduction', to='reports.ExtraSummaryReportInfo'),
        ),
    ]
