dist: bionic
language: python

python:
  - "3.8"

services:
  - mysql

env:
  - DJANGO=3.0 DB=mysql

before_install:
  - mysql -e 'DROP DATABASE IF EXISTS payroll_schema;'
  - mysql -e 'CREATE DATABASE payroll_schema;'

install:
  - pip install -r requirements.txt

script: python manage.py test
