language: python

python:
  - "3.6"

before_script:
  - mysqld_safe --skip-grant-tables &
  - mysql
  - UPDATE mysql.user SET Password=PASSWORD('Kam12345') WHERE User='root';
  - FLUSH PRIVILEGES;
  - exit;
  - mysqladmin -u root -p Kam12345 shutdown
  - service mysql start

services:
  - mysql

env:
  - DJANGO=2.2 DB=mysql

install:
  - pip install -r requirements.txt

script: python manage.py test
