language: python

python:
  - "3.6"

services:
  - mysql

env:
  - DJANGO=2.2 DB=mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database payroll_schema;' -u root
  - python manage.py migrate
  - python manage.py runserver --settings=hr_system.test_settings

script: python manage.py test
