language: python

python:
  - "3.6"
  - "3.7"

services:
  - mysql

env:
  - DJANGO=2.2 DB=mysql
  - SECRET_KEY=141b364869dd5b23831d1cad86b05342

install:
  - pip install -r requirements.txt

script: python manage.py test
