# Generated by Django 2.2 on 2019-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriodReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
