# Generated by Django 2.2b1 on 2019-03-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('payroll', '0004_auto_20190329_1231'),
        ('users', '0005_delete_payrollperiodreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriodReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('nssf', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
                ('lst',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.LSTRates')),
                ('paye',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PAYERates')),
                ('payroll_period',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollPeriod')),
            ],
        ),
    ]
