# Generated by Django 2.2 on 2019-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExTraSummaryReportInfo',
            fields=[
                ('key', models.CharField(blank=True, default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_earning', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
