# Generated by Django 2.2b1 on 2019-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='gross_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='lst',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='nssf',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='paye',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiodreport',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
