# Generated by Django 3.0.6 on 2020-05-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('payroll', '0002_auto_20200520_1742'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='users.Employee'),
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='payroll_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
