# Generated by Django 2.2 on 2019-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('payroll', '0002_auto_20190521_1443'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='payroll_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
