# Generated by Django 2.2b1 on 2019-03-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='payroll_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollPeriod'),
        ),
    ]
