# Generated by Django 2.2 on 2019-04-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        ('payroll', '0002_auto_20190411_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
        ),
        migrations.AddField(
            model_name='payrollperiodreport',
            name='payroll_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
    ]
