# Generated by Django 2.2 on 2019-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190419_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='gross_earning',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
