# Generated by Django 3.0.6 on 2020-06-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200604_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrasummaryreportinfo',
            old_name='employee_name',
            new_name='staff_full_name',
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='gross_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
