# Generated by Django 2.2 on 2019-04-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190403_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollperiodreport',
            old_name='Car_transport_allowance',
            new_name='car_transport_allowance',
        ),
    ]
