# Generated by Django 3.0.6 on 2020-06-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200604_0357'),
        ('payroll', '0007_auto_20200602_0958'),
        ('reports', '0004_auto_20200604_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod'),
        ),
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='report_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
