# Generated by Django 2.2 on 2019-07-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190727_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='users.Employee'),
        ),
    ]
