# Generated by Django 3.0.6 on 2020-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200604_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrasummaryreportinfo',
            options={'ordering': ['-payroll_period__created_on', 'staff_full_name'], 'verbose_name': 'Summary report', 'verbose_name_plural': 'Summary reports'},
        ),
        migrations.AddField(
            model_name='extrasummaryreportinfo',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
