# Generated by Django 3.0.6 on 2020-06-04 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_extrasummaryreportinfo_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='period',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
