# Generated by Django 3.0.6 on 2020-06-04 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200602_0958'),
        ('reports', '0008_auto_20200604_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='report_id',
            field=models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True),
        )
    ]
