# Generated by Django 3.0.6 on 2020-06-05 02:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200602_0958'),
        ('reports', '0010_auto_20200604_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxationreport',
            options={'ordering': ['-period', 'staff_full_name'], 'verbose_name': 'PAYE report', 'verbose_name_plural': 'PAYE reports'},
        ),
        migrations.RemoveField(
            model_name='taxationreport',
            name='cost_centre',
        ),
        migrations.AddField(
            model_name='taxationreport',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxationreport',
            name='report_id',
            field=models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taxationreport',
            name='staff_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='LSTReport',
            fields=[
                ('report_id', models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('period', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('staff_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('duty_station', models.CharField(blank=True, max_length=150, null=True)),
                ('gross_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod')),
            ],
            options={
                'verbose_name': 'LST report',
                'verbose_name_plural': 'LST reports',
                'ordering': ['-period', 'staff_full_name'],
            },
        )
    ]
