# Generated by Django 3.0.6 on 2020-06-05 02:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200602_0958'),
        ('reports', '0011_auto_20200605_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSecurityReport',
            fields=[
                ('report_id', models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('period', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('staff_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('agresso_number', models.CharField(blank=True, max_length=15, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=25, null=True)),
                ('duty_station', models.CharField(blank=True, max_length=150, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('gross_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nssf_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nssf_10', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod')),
            ],
            options={
                'verbose_name': 'NSSF report',
                'verbose_name_plural': 'NSSF reports',
                'ordering': ['-period', 'staff_full_name'],
            },
        ),
    ]
