# Generated by Django 3.0.6 on 2020-06-05 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200602_0958'),
        ('reports', '0009_auto_20200604_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('staff_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('report_id', models.CharField(editable=False, max_length=50)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_code', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.PayrollPeriod')),
            ],
            options={
                'verbose_name': 'BANK report',
                'verbose_name_plural': 'BANK reports',
                'ordering': ['-period', 'staff_full_name'],
            },
        ),
    ]
