# Generated by Django 3.0.6 on 2020-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_bankreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreport',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankreport',
            name='report_id',
            field=models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
