# Generated by Django 3.0.6 on 2020-09-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20200605_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreport',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_summary_report', to='reports.ExtraSummaryReportInfo'),
        ),
        migrations.AddField(
            model_name='lstreport',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lst_summary_report', to='reports.ExtraSummaryReportInfo'),
        ),
        migrations.AddField(
            model_name='socialsecurityreport',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_summary_report', to='reports.ExtraSummaryReportInfo'),
        ),
        migrations.AddField(
            model_name='taxationreport',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxation_summary_report', to='reports.ExtraSummaryReportInfo'),
        ),
    ]
