# Generated by Django 3.0.6 on 2020-09-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200924_0845'),
        # ('reports', '0016_auto_20200924_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasummaryreportinfo',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='users.Employee'),
        ),
    ]
