# Generated by Django 3.0.6 on 2020-10-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20200924_1146'),
        ('reports', '0011_auto_20200605_0235'),
        ('reports', '0014_auto_20200605_0638'),
    ]

    operations = [
    ]
