# Generated by Django 2.2.7 on 2019-11-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('support_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payroll_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollCenter'),
        ),
        migrations.AddField(
            model_name='payrollcentereds',
            name='ed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EarningDeductionType'),
        ),
        migrations.AddField(
            model_name='payrollcentereds',
            name='payroll_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollCenter'),
        ),
        migrations.AddField(
            model_name='payrollcenter',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_data.Country'),
        ),
        migrations.AddField(
            model_name='payrollcenter',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='support_data.Organization'),
        ),
        migrations.AddField(
            model_name='lstrates',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_data.Country'),
        ),
        migrations.AddField(
            model_name='earningdeductiontype',
            name='ed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.EarningDeductionCategory'),
        ),
    ]
