# Generated by Django 2.2 on 2019-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190521_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdeductiontype',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='earningdeductiontype',
            name='agresso_type',
            field=models.CharField(blank=True, choices=[('SALARY COSTS', 'SALARY COSTS'), ('SALARIES', 'SALARIES'), ('BENEFITS', 'BENEFITS'), ('OVERTIME', 'OVERTIME'), ('SALARY ADVANCES', 'SALARY ADVANCES'), ('EMPLOYEE PENSION', 'EMPLOYEE PENSION'), ('DEDUCTIONS', 'DEDUCTIONS'), ('PENSION COSTS', 'PENSION COSTS'), ('SOCIAL SECURITY', 'SOCIAL SECURITY'), ('PAYMENTS', 'PAYMENTS'), ('ACCRUED PAYROLL', 'ACCRUED PAYROLL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='earningdeductiontype',
            name='factor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='earningdeductiontype',
            name='summarize',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, null=True),
        ),
    ]
