# Generated by Django 2.2 on 2019-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190411_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.IntegerField()),
                ('account_name', models.CharField(max_length=150)),
            ],
        ),
    ]
