# Generated by Django 2.2 on 2019-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190518_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdeductiontype',
            name='debit_credit_sign',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='earningdeductiontype',
            name='account_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
