# Generated by Django 2.2b1 on 2019-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190320_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='payroll_key',
            field=models.CharField(blank=True, default='Auto', max_length=15),
        ),
    ]
