# Generated by Django 2.2b1 on 2019-03-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0002_auto_20190329_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=6),
        ),
    ]
