# Generated by Django 2.2 on 2019-05-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190505_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'permissions': [('close_payrollperiod', 'Can close payroll period'), ('process_payrollperiod', 'Can process payroll period')]},
        ),
    ]
