# Generated by Django 2.2 on 2019-04-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdeductiontype',
            name='account_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.Account'),
        ),
        migrations.AddField(
            model_name='earningdeductiontype',
            name='export',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=3, null=True),
        ),
    ]
