# Generated by Django 2.2 on 2019-05-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190528_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='sort_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
