# Generated by Django 2.2 on 2019-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190505_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcentereds',
            name='pced_key',
            field=models.CharField(blank=True, default=None, max_length=150, unique=True),
        ),
    ]
