# Generated by Django 2.2b1 on 2019-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0003_auto_20190325_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcenter',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='support_data.Organization'),
        ),
    ]
