# Generated by Django 2.2 on 2019-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20191004_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummaryApprovals',
            fields=[
                ('date_of_approval', models.DateField(auto_created=True)),
                ('approver_names', models.CharField(max_length=300)),
                ('payroll_summary', models.CharField(max_length=300)),
                ('signature', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
