# Generated by Django 2.2b1 on 2019-03-29 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('support_data', '0001_initial'),
        ('payroll', '0003_auto_20190329_0331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ISRates',
            new_name='LSTRates',
        ),
    ]
