# Generated by Django 2.2 on 2019-10-04 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollsummaryapprovals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsummaryapprovals',
            name='date_of_approval',
            field=models.DateField(default=datetime.datetime(2019, 10, 4, 17, 16, 8, 900088, tzinfo=utc)),
        ),
    ]
