# Generated by Django 2.2b1 on 2019-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20190320_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='payroll_key',
            field=models.CharField(blank=True, default='Auto generated', max_length=150),
        ),
    ]
