# Generated by Django 2.2 on 2019-05-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollcentereds_pced_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
