# Generated by Django 2.2 on 2019-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20190403_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='payroll_key',
            field=models.CharField(blank=True, default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(default='OPEN', max_length=6),
        ),
    ]
