# Generated by Django 2.2b1 on 2019-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0005_auto_20190329_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstrates',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lstrates',
            name='lower_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lstrates',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lstrates',
            name='upper_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payerates',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payerates',
            name='lower_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payerates',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payerates',
            name='upper_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
