# Generated by Django 2.2 on 2019-10-04 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20191004_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsummaryapprovals',
            name='date_of_approval',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
