# Generated by Django 2.2b1 on 2019-03-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0006_auto_20190329_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollcenterEds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='payroll.EarningDeductionType')),
                ('payroll_center',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayrollCenter')),
            ],
        ),
    ]
