# Generated by Django 2.2 on 2019-06-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20190604_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningdeductiontype',
            name='cost_centre',
        ),
    ]
