# Generated by Django 2.2 on 2019-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_remove_earningdeductiontype_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningdeductiontype',
            name='display_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
