# Generated by Django 3.0.6 on 2020-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20200625_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
