# Generated by Django 2.2 on 2019-07-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20190722_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='description',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
