# Generated by Django 3.0.6 on 2020-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_earningdeductiontype_usable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningdeductiontype',
            name='display_number',
            field=models.IntegerField(blank=True, default=1001, null=True),
        ),
    ]
