# Generated by Django 2.2b1 on 2019-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], default=2019),
        ),
    ]
