# Generated by Django 2.2 on 2019-05-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollcentereds_pced_key'),
        ('support_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystation',
            name='earnings_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EarningDeductionType'),
        ),
    ]
