# Generated by Django 2.2 on 2019-09-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
