# Generated by Django 2.2 on 2019-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0002_dutystation_earnings_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystation',
            name='earning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
