# Generated by Django 2.2 on 2019-09-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_data', '0002_movementparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollApprovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_1', to=settings.AUTH_USER_MODEL)),
                ('approver_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_2', to=settings.AUTH_USER_MODEL)),
                ('approver_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
