# Generated by Django 2.2 on 2019-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0002_auto_20190518_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='leave_days_entitled',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
    ]
