# Generated by Django 2.2 on 2019-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0003_dutystation_earning_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutystation',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
