# Generated by Django 2.2 on 2019-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0003_auto_20190518_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
