# Generated by Django 2.2 on 2019-09-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0004_auto_20190918_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollapprover',
            name='approver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
