# Generated by Django 2.2 on 2019-10-09 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_data', '0005_auto_20190918_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='leave_days_entitled',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
